#! /bin/bash

function showUsage () {
  echo "compileAgdaTex <agda-lib> <dst>"
  echo ""
  echo "Will compile every literate Agda module from <agda-lib>"
  echo "to a latex file in <dst>."
  echo ""
  echo "<dst> must be relative to the current directory."
  echo "<agda-lib> has to have a file named *.agda-lib"
  echo ""
}
  

if (( $# != 2 )); then
  showUsage
  exit 1
fi

LIB=$1
DST=$2

LIBfile=$(ls $LIB/*.agda-lib)
if [[ -z $LIBfile ]]; then
  echo "Can't find $LIB/*.agda-lib file."
  exit 1
fi

LIBsrc=$(cat $LIBfile | grep "include")
LIBsrc=${LIBsrc:9}
if [[ -z $LIBsrc ]]; then
  echo "$LIBfile doesn't have an 'include' field."
  exit 1
fi

HERE=$(pwd)

# Start logfile
LOG=$HERE/compileAgdaTex.log
date > $LOG

# Keep a flag around!
STATUS=0

# Start compiling
LIBPATH=$(dirname $LIBfile)/$LIBsrc
cd $LIBPATH
for i in $(find . -name "*.lagda"); do
  agda --allow-unsolved-metas --latex-dir=$HERE/$DST --latex $i
  
  #Whenever we fail, log that file but keep going!
  if (( $? != 0 )); then
    STATUS=$?
    echo -e "$i :\n\t $STATUS\n" >> $LOG
  fi
done
cd $HERE

